# Generated by Django 5.1.7 on 2025-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_icon', models.ImageField(default='/users/dft_profile.jpg', upload_to='users')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('unicode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
