# Generated by Django 5.1.7 on 2025-04-20 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/users/dft_profile.jpg', upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unicode',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
