# Generated by Django 5.1.7 on 2025-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0003_delete_users_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='', upload_to='users/'),
        ),
    ]
