# Generated by Django 5.1.7 on 2025-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0006_bigcategory_setting_smallcategory_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallcategory',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(1, '支出'), (2, '收入'), (3, '物品收入')], verbose_name='类型'),
        ),
    ]
