# Generated by Django 5.1.7 on 2025-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0007_smallcategory_icon_alter_cashflow_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcategory',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '支出'), (2, '收入')], default=1, verbose_name='类型'),
        ),
    ]
