# Generated by Django 5.1.7 on 2025-05-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0008_bigcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='item_name',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='amortization_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='摊销天数'),
        ),
    ]
