# Generated by Django 5.1.7 on 2025-05-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0009_cashflow_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcategory',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '支出'), (2, '收入'), (3, '物品收入')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='item_name',
            field=models.TextField(blank=True, null=True, verbose_name='物品名称'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leading_group', to=settings.AUTH_USER_MODEL, verbose_name='组长')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='MIL.group', verbose_name='所属组'),
        ),
    ]
