# Generated by Django 5.1.7 on 2025-05-14 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0010_alter_bigcategory_type_alter_cashflow_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, '未决定'), (2, '接受'), (3, '拒绝')], default=1, verbose_name='状态')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
        ),
    ]
