# Generated by Django 5.1.7 on 2025-05-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0011_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='user',
        ),
    ]
