# Generated by Django 5.1.7 on 2025-05-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0015_remove_setting_occurdate_setting_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MIL.smallcategory'),
        ),
    ]
