# Generated by Django 5.1.7 on 2025-05-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0016_alter_setting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='small_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MIL.smallcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '支出'), (2, '收入')], verbose_name='类型'),
        ),
    ]
