# Generated by Django 5.1.7 on 2025-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0017_setting_small_category_alter_setting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcategory',
            name='icon',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
