# Generated by Django 5.1.7 on 2025-06-02 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0018_bigcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原始金额')),
                ('amortized_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='摊销金额')),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('amortization_date', models.DateField(verbose_name='摊销日期')),
                ('transaction_type', models.SmallIntegerField(choices=[(1, '支出'), (2, '收入'), (3, '物品收入')], verbose_name='类型')),
                ('is_amortized', models.BooleanField(default=False, verbose_name='是否摊销')),
                ('amortization_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='摊销期数')),
                ('current_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='当前期数')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('cash_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MIL.cashflow', verbose_name='关联现金流')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MIL.smallcategory', verbose_name='小分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '利润明细',
                'verbose_name_plural': '利润明细',
                'ordering': ['-amortization_date'],
            },
        ),
    ]
