# Generated by Django 5.1.7 on 2025-06-04 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0019_profitdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='统计年份')),
                ('month', models.PositiveIntegerField(verbose_name='统计月份(1-12)')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总收入')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总支出')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='净利润')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_profits', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '月度利润统计',
                'verbose_name_plural': '月度利润统计',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
