# Generated by Django 5.1.7 on 2025-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIL', '0021_bigcategory_user_smallcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallcategory',
            name='icon',
            field=models.ImageField(default='icons/default.png', upload_to='icons/'),
        ),
    ]
